### ISSUE TITLE
Reconnecting (missing auth)

### ISSUE THREAD

**Issue by volksport** [CodementorIO/rest-firebase#9]
So I added RestFirebase::Error::ClientError to my :retry_exceptions and I'm sometimes seeing this during reconnects (first one is from onerror, second is from rest-firebase):
```
My Errors: Please set your secret RestFirebase::Error::ClientError
RestCore: ERROR: Please set your secret
```

It appears to be hitting onerror properly, shouldn't that catch it, and not bubble up to a failure? But moreso, why is this happening? The auth is in fact being set during the initial connection (and properly connects), maybe it loses track of it for reconnecting?

```
from [
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-firebase-e825acb062da/lib/rest-firebase.rb:89:in `generate_auth'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-firebase-e825acb062da/lib/rest-firebase.rb:107:in `default_auth'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:376:in `auth'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-firebase-e825acb062da/lib/rest-firebase.rb:102:in `query'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:56:in `block in attributes'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:56:in `each_pair'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:56:in `each'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:56:in `map'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:56:in `attributes'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:194:in `build_env'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:166:in `request_full'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:159:in `request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-firebase-e825acb062da/lib/rest-firebase.rb:85:in `request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:100:in `get'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:129:in `reconnect'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:89:in `onreconnect'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:71:in `onerror'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:52:in `rescue in onopen'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:38:in `onopen'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:133:in `block in reconnect'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:159:in `block in request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:167:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:167:in `block in request_full'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/retry.rb:20:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/retry.rb:20:in `process'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/retry.rb:14:in `block in call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:18:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:18:in `process'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:12:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_handler.rb:16:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_detector.rb:11:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/json_response.rb:26:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/common_logger.rb:13:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/cache.rb:35:in `block in app_call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:199:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:199:in `block in callback'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:193:in `each'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:193:in `inject'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:193:in `callback'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:145:in `fulfilling'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:106:in `block in fulfill'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:106:in `synchronize'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:106:in `fulfill'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine/http-client.rb:38:in `request_async'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine/http-client.rb:20:in `request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine.rb:12:in `block in call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:85:in `block (2 levels) in defer'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:163:in `block in protected_yield'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:185:in `timeout_protected_yield'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:163:in `protected_yield'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:85:in `block in defer'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine.rb:12:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/cache.rb:30:in `app_call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/cache.rb:26:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/common_logger.rb:12:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/json_response.rb:24:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_detector.rb:9:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_handler.rb:9:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:12:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:29:in `process'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:12:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_handler.rb:16:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_detector.rb:11:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/json_response.rb:26:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/common_logger.rb:13:in `block in call'",
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/cache.rb:35:in `block in app_call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:199:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:199:in `block in callback'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:193:in `each'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:193:in `inject'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:193:in `callback'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:145:in `fulfilling'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:106:in `block in fulfill'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:106:in `synchronize'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:106:in `fulfill'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine/http-client.rb:38:in `request_async'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine/http-client.rb:20:in `request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine.rb:12:in `block in call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:85:in `block (2 levels) in defer'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:163:in `block in protected_yield'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:185:in `timeout_protected_yield'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:163:in `protected_yield'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/promise.rb:85:in `block in defer'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/engine.rb:12:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/cache.rb:30:in `app_call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/cache.rb:26:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/common_logger.rb:12:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/json_response.rb:24:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_detector.rb:9:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/error_handler.rb:9:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/follow_redirect.rb:12:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/timeout.rb:18:in `process'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/timeout.rb:13:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/retry.rb:14:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/json_request.rb:13:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/default_query.rb:9:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/default_headers.rb:9:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/middleware/default_site.rb:15:in `call'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:166:in `request_full'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:159:in `request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-firebase-e825acb062da/lib/rest-firebase.rb:85:in `request'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/client.rb:100:in `get'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:129:in `reconnect'", 
"/app/vendor/bundle/ruby/2.1.0/bundler/gems/rest-core-c169272abccf/lib/rest-core/event_source.rb:18:in `start'", 
"/app/lib/daemons/disconnected.rb:86:in `<top (required)>'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:218:in `load'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:218:in `start_load'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:297:in `start'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:59:in `run'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:144:in `block in run'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'",
"/app/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:143:in `run'",
"/app/lib/daemons/disconnected_control.rb:3:in `<main>'"
```

**Comment by godfat** [comment]
This was happening because you didn't pass the secret to rest-firebase, I think? The default `auth_ttl` is 82800, which means for each 23 hours, rest-firebase would try to regenerate the auth. This is the default because as far as I know, Firebase token would expire after 24 hours.

If you do not like this behaviour, you could pass `auth_ttl` to false to disable this behaviour:

``` ruby
f = RestFirebase.new(:auth_ttl => false)
# or
f.auth_ttl = false
```

On the other hand, you should probably not add `RestFirebase::Error::ClientError` to `:retry_exceptions` because this exception was used for the client/application, therefore it would be an issue which could not simply recover from itself from retrying. In your case, you need to either set `secret` or disable `auth_ttl`.

**Comment by volksport** [comment]
Trying your suggestion of adding auth_ttl => false, and removing the retry exception for ClientError. I can't remember exactly why -- and I made this change a long time ago, but I'm using my secret key as :auth as it seemed to work whereas :secret did not. But again, it was a while ago and I don't remember fully why I had to make that change. Will see how this goes.

**Comment by godfat** [comment]
Oh. IIRC you could also use your secret as the auth token, and it would never expire. I never used this approach and forgot it entirely.

In the early days, there were some auth refreshing issue, around Aug 2014 or so (just checked commit log). But I think self-refreshing is working properly now, at least I never saw expired token exception for a long time. (we used to see them occasionally)

I would suggest pass the secret and leave auth alone and let rest-firebase generate the auth token for you, so that you won't expose your secret over the air (though HTTPS protected, there could have logs)
